# Don't be alarmed by the use of colons in the key, as
# long as it's not followed by a space...
#

dcgov.openmedia.dev: ABQIAAAAgJjchvoGlgLArly2J2boERR5u0tYEz6g9NizfF0NBDyuo6gh8BQ2P3ez2RXZcy1GJQkZVFiDULWxRA

dc.openmedia.dev: ABQIAAAAgJjchvoGlgLArly2J2boERRVFwUMeuY0zuAHwD9n-dhZEHujbxSgnnQYoh-GOZmj2e_oHzNY90ugFQ
localhost:3000: ABQIAAAAzVvei_aST8WVucxkoiLYRBTJQa0g3IQ9GZqIMmInSLzwtGDKaBTkhH76aYPcy-ztKbg2PUP4Iv2Klw
localhost:3000/gmap/: ABQIAAAAzVvei_aST8WVucxkoiLYRBSbmUDxPddGxnDJiyLDHUG8C2Vq9RRj-LQeQHkxp9oO9nzQ-Og4B7jXxA