base: &base

development:
  host: localhost
  port: 5984
  database_suffix: _<%= Rails.env %>
  <<: *base

dev_server:
  host: localhost
  port: 5984
  database_suffix: _<%= Rails.env %>
  <<: *base
  
test:
  host: localhost
  port: 5984
  database_suffix: _<%= Rails.env %>
  <<: *base
